packages:
  - dnf-utils 
  - createrepo_c
  - cronie

repo_name: rocky9

mirror_command: dnf reposync --repoid=rocky9-baseos --repoid=rocky9-appstream --download-metadata --delete --destdir={{ repos_path }}/{{ repo_name }}
# mirror_command: dnf reposync --repoid=rocky9-baseos --repoid=rocky9-appstream --repoid=rocky9-crb --repoid=rocky9-extras --download-metadata --delete --destdir={{ repos_path }}/{{ repo_name }}

repo_config_dest: '/etc/yum.repos.d/rocky9.repo'

repos_links: 
  - { src: "{{ repos_path }}/{{ repo_name }}", dest: "{{ nginx_path }}/{{ repo_name }}" }
