---

- name: DNS Firewall Setup
  community.general.ufw:
    rule: allow
    port: dns # 53
    src: "{{ INTERNAL_NETWORK }}/{{ MASK }}"
  when: #"'ufw' in ansible_facts.packages"
    - ansible_facts.services is defined
    - ansible_facts.services['ufw.service'] is defined
    - ansible_facts.services['ufw.service'].state == 'running'